### ISSUE TITLE
Am trying to understand how to run web and worker separately 

### ISSUE THREAD

**Issue by mwaaas** [learnk8s/spring-boot-k8s-hpa#3]
So I have looked at your code. I see the way you are running backend and worker separately is by using the environment variable then using that environment variable to set up JMS listeners. 
But with that approach, it means in the backend you will still run the backend and worker altogether. Since Spring application will start web by default.

**Comment by danielepolencic** [comment]
It's not how I would structure apps normally. This is just an example aimed at explaining scaling in Kubernetes.
In real life, I'd have two apps: one for the backend and one for the worker that don't share any code (unless they use common libraries, etc.).
The backend worker is not activated if you only activate the worker. And vice-versa.
You can test the app by launching it as a backend and queuing tickets (nothing happens). As soon as you add a worker (or backend&worker) app, the queue is consumed.

**Comment by mwaaas** [comment]
thanks for taking the time to answer me.
