### ISSUE TITLE
error: unable to recognize "monitoring/metrics-server/metrics-server-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by ehabsoa** [learnk8s/spring-boot-k8s-hpa#5]
Hi, 

I am getting this error:

**error: unable to recognize "monitoring/metrics-server/metrics-server-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"**

while I executed this command:

**kubectl create -f monitoring/metrics-server**

I am using Minikube version: **v1.5.2**

Thanks.

**Comment by danielepolencic** [comment]
The `extensions/v1beta1` API isn't available in Kubernetes 1.16
I updated the resources to use the new `apps/v1` API. It should work now.

Thanks for reporting this.

**Comment by ehabsoa** [comment]
Thanks a lot for your help. 
Could you please update "monitoring/metrics-server/metrics-server-deployment.yaml". It's still using the old version:

**error: unable to recognize "monitoring/metrics-server/metrics-server-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"**

Thank you.
