### ISSUE TITLE
packaging and running this on minikube / windows possible ?

### ISSUE THREAD

**Issue by samuelTharma** [learnk8s/spring-boot-k8s-hpa#7]
I am trying to package and deploy this in windows - but no luck,
appreciate your input on whether it's possible? 

when I run docker build -t spring-boot-hpa . its created the image successfully

when I deploy in minikube using kubectl create -f kube/deployment

get the following 

backend-7f8577cdd5-tbs4w    0/1     ContainerCreating   0          67m
frontend-559bd7c667-5gnh7   0/1     ContainerCreating   0          67m
queue-58cf455966-64qn2      0/1     ContainerCreating   0          67m

**Comment by danielepolencic** [comment]
That's good? There's no error so far.

**Comment by samuelTharma** [comment]
The issue was, eval $(minikube docker-env) didn't work in windows. Now able to see this working after running on bash command tool.
thank you

**Comment by danielepolencic** [comment]
Ah, well spotted!
